#!/bin/bash
#
# generate_theme.sh - Generate embedded theme header from theme files
# Copyright (C) 2025
# SPDX-License-Identifier: BSD-2-Clause
#
# This script converts theme files into C header format for embedding
# directly into the nginx fancyindex module.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
THEME_DIR="${SCRIPT_DIR}/theme"
OUTPUT_FILE="${SCRIPT_DIR}/theme_builtin.h"

# Function to convert a file to C byte array using od (portable, no xxd needed)
file_to_c_array() {
    local file="$1"
    local varname="$2"
    local mime="$3"

    if [ ! -f "$file" ]; then
        echo "Warning: File not found: $file" >&2
        return 1
    fi

    local size=$(wc -c < "$file" | tr -d ' ')

    echo "/* ${file##*/} - ${mime} */"
    echo "static const u_char nfi_theme_${varname}_mime[] = \"${mime}\";"
    echo "static const size_t nfi_theme_${varname}_len = ${size};"
    echo "static const u_char nfi_theme_${varname}_data[] = {"

    # Use od to convert to hex and format as C array (portable)
    # od outputs hex bytes, we convert to C hex format
    od -An -tx1 -v "$file" | \
        awk '
        BEGIN { first = 1 }
        {
            for (i = 1; i <= NF; i++) {
                if (!first) printf ", "
                printf "0x%s", $i
                first = 0
            }
            printf "\n"
        }
        ' | \
        sed 's/^/    /'

    echo "};"
    echo ""
}

# Generate header
cat > "$OUTPUT_FILE" << 'HEADER'
/*
 * theme_builtin.h - Embedded theme assets for ngx_http_fancyindex_module
 * Automagically generated by generate_theme.sh - do not edit!
 *
 * This file contains the built-in theme assets that are served directly
 * from the module without needing external files.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#ifndef NGX_FANCYINDEX_THEME_BUILTIN_H
#define NGX_FANCYINDEX_THEME_BUILTIN_H

HEADER

# Generate CSS
echo "/* ========================================" >> "$OUTPUT_FILE"
echo "   Embedded CSS stylesheet" >> "$OUTPUT_FILE"
echo "   ======================================== */" >> "$OUTPUT_FILE"
file_to_c_array "${THEME_DIR}/styles.css" "css" "text/css; charset=utf-8" >> "$OUTPUT_FILE"

# Generate JavaScript
echo "/* ========================================" >> "$OUTPUT_FILE"
echo "   Embedded JavaScript" >> "$OUTPUT_FILE"
echo "   ======================================== */" >> "$OUTPUT_FILE"
file_to_c_array "${THEME_DIR}/addNginxFancyIndexForm.js" "js" "application/javascript; charset=utf-8" >> "$OUTPUT_FILE"

# Generate header HTML (modified for built-in use)
echo "/* ========================================" >> "$OUTPUT_FILE"
echo "   Embedded header HTML" >> "$OUTPUT_FILE"
echo "   ======================================== */" >> "$OUTPUT_FILE"
file_to_c_array "${THEME_DIR}/header.html" "header" "text/html; charset=utf-8" >> "$OUTPUT_FILE"

# Generate footer HTML (modified for built-in use)
echo "/* ========================================" >> "$OUTPUT_FILE"
echo "   Embedded footer HTML" >> "$OUTPUT_FILE"
echo "   ======================================== */" >> "$OUTPUT_FILE"
file_to_c_array "${THEME_DIR}/footer.html" "footer" "text/html; charset=utf-8" >> "$OUTPUT_FILE"

# Close header guard and add constants
cat >> "$OUTPUT_FILE" << 'FOOTER'

/* ========================================
   Theme configuration constants
   ======================================== */

/* Theme asset path prefix - requests to this path serve embedded assets */
#define NFI_THEME_PATH_PREFIX "/_nfi_theme"
#define NFI_THEME_PATH_PREFIX_LEN 11

/* Asset paths for embedded theme */
#define NFI_THEME_CSS_PATH "/_nfi_theme/styles.css"
#define NFI_THEME_JS_PATH "/_nfi_theme/fancyindex.js"

/* Asset enumeration */
typedef enum {
    NFI_THEME_ASSET_CSS,
    NFI_THEME_ASSET_JS,
    NFI_THEME_ASSET_NONE
} nfi_theme_asset_t;

/* Lookup table for theme assets */
typedef struct {
    const char          *path;
    size_t               path_len;
    const u_char        *mime;
    size_t               mime_len;
    const u_char        *data;
    size_t               data_len;
} nfi_theme_asset_info_t;

static const nfi_theme_asset_info_t nfi_theme_assets[] = {
    {
        "/styles.css",
        11,
        nfi_theme_css_mime,
        sizeof(nfi_theme_css_mime) - 1,
        nfi_theme_css_data,
        nfi_theme_css_len
    },
    {
        "/fancyindex.js",
        14,
        nfi_theme_js_mime,
        sizeof(nfi_theme_js_mime) - 1,
        nfi_theme_js_data,
        nfi_theme_js_len
    },
    { NULL, 0, NULL, 0, NULL, 0 }
};

#endif /* NGX_FANCYINDEX_THEME_BUILTIN_H */
FOOTER

echo "Generated: $OUTPUT_FILE"
echo "Theme files embedded successfully."

# Show file sizes
echo ""
echo "Embedded assets:"
for f in "${THEME_DIR}/styles.css" "${THEME_DIR}/addNginxFancyIndexForm.js" "${THEME_DIR}/header.html" "${THEME_DIR}/footer.html"; do
    if [ -f "$f" ]; then
        size=$(wc -c < "$f" | tr -d ' ')
        echo "  ${f##*/}: ${size} bytes"
    fi
done

total_size=$(wc -c < "$OUTPUT_FILE" | tr -d ' ')
echo ""
echo "Total generated header size: ${total_size} bytes"
